import Link from "next/link";
import { pageMetadata } from "../../lib/seo";
import "./policy.css";

export const metadata = pageMetadata({
  title: "Política de Privacidade | Invest.ao",
  description: "Como a Invest.ao recolhe, utiliza, conserva e elimina os seus dados pessoais.",
  path: "/policy",
});

export default function PrivacyPolicy() {
  return (
    <main className="policy-page" lang="pt-PT">
      <nav aria-label="Navegação da política"><Link href="/">invest.ao</Link><Link href="/">Voltar ao início</Link></nav>
      <header><span>OS SEUS DADOS</span><h1>Política de Privacidade</h1><p>Última atualização: 15 de setembro de 2026</p></header>
      <p>Esta política explica como a Invest.ao trata os dados pessoais quando utiliza a nossa aplicação para iPhone e o nosso sítio Web. A Invest.ao permite acompanhar o mercado de capitais angolano, guardar favoritos e organizar uma carteira. Não executa ordens de compra ou venda de títulos.</p>
      <section><h2>1. Dados que recolhemos</h2>
        <ul>
          <li><strong>Dados da conta.</strong> Quando inicia sessão com a Google ou a Apple, recebemos um identificador de conta e os dados de perfil disponibilizados pelo respetivo fornecedor, como o nome e o endereço de correio eletrónico. A Apple pode fornecer um endereço de correio eletrónico privado de reencaminhamento. Não recebemos a palavra-passe da sua conta Google ou Apple.</li>
          <li><strong>Informações que guarda.</strong> Incluem os títulos favoritos, a ordem da lista de acompanhamento, as regras e preferências de alertas e os registos de carteira que decide introduzir: título, tipo de operação (compra ou venda), quantidade, preço unitário e data. O registo de uma operação não dá origem a uma ordem de negociação.</li>
          <li><strong>Dados de notificações.</strong> Se ativar as notificações, tratamos um identificador de notificações push, um identificador da instalação da aplicação, a versão e o número de compilação da aplicação, as preferências de notificação e os estados de entrega ou leitura necessários ao funcionamento dos alertas.</li>
          <li><strong>Dados técnicos.</strong> Os pedidos aos nossos serviços disponibilizam à infraestrutura de alojamento informações como o endereço IP e os detalhes do pedido. Os registos operacionais podem incluir datas e horas, eventos de autenticação, erros e resultados da entrega de notificações, para fins de segurança e resolução de problemas.</li>
          <li><strong>Mensagens que nos envia.</strong> Se nos contactar, tratamos os dados de contacto e as informações que fornecer para responder ao seu pedido. Não envie palavras-passe nem informações financeiras desnecessárias.</li>
        </ul>
      </section>
      <section><h2>2. Como utilizamos os dados</h2><p>Utilizamos estes dados para autenticar a sua conta, sincronizar as informações que guarda, apresentar a sua carteira, entregar os alertas que configura, memorizar as suas definições, responder a pedidos e manter a fiabilidade e a segurança do serviço. Não utilizamos os registos da sua carteira para executar transações.</p></section>
      <section><h2>3. Armazenamento no dispositivo e controlos de privacidade</h2><p>A aplicação guarda informações de sessão, preferências e dados em cache no seu dispositivo. Os widgets podem utilizar dados partilhados localmente entre a aplicação e a extensão de widgets. O modo de privacidade oculta os valores pessoais abrangidos no ecrã; não elimina os dados subjacentes nem impede o serviço na nuvem de guardar as informações necessárias à sua conta.</p><p>Pode alterar as permissões de notificação nas Definições do iOS e gerir as preferências de alertas disponíveis na aplicação. Desativar as notificações não elimina a sua conta.</p></section>
      <section><h2>4. Prestadores de serviços e partilha de dados</h2><p>Utilizamos a Supabase para a autenticação de contas, o armazenamento em base de dados e os serviços de suporte à aplicação. A Google e a Apple tratam o início de sessão de acordo com o método escolhido. O serviço de notificações push da Apple entrega as notificações ativadas. Os prestadores de alojamento e infraestrutura tratam os dados técnicos necessários ao funcionamento da aplicação e do sítio Web.</p><p>Partilhamos dados com estes prestadores na medida necessária à prestação do serviço. Os dados também podem ser divulgados quando tal seja exigido por lei ou para investigar utilizações indevidas e proteger a segurança ou os direitos dos utilizadores e do serviço. A sua carteira e os seus favoritos não são publicados como parte da informação pública de mercado.</p><p>Os prestadores podem tratar dados fora do seu país. Os seus serviços estão também sujeitos às respetivas políticas de privacidade: <a href="https://supabase.com/privacy">Supabase</a>, <a href="https://www.apple.com/legal/privacy/">Apple</a> e <a href="https://policies.google.com/privacy">Google</a>.</p></section>
      <section><h2>5. Publicidade e rastreio</h2><p>A versão atual da aplicação não inclui publicidade nem rastreio entre aplicações para fins publicitários. Não vendemos os seus dados pessoais nem utilizamos a sua carteira e os seus favoritos para publicidade direcionada.</p></section>
      <section><h2>6. Conservação dos dados e eliminação da conta</h2><p>Conservamos os dados da conta e os conteúdos guardados enquanto forem necessários para disponibilizar a sua conta e as funcionalidades que utiliza. Para eliminar a conta, abra as definições da aplicação, escolha <strong>«Eliminar conta»</strong> e confirme. Quando a eliminação é concluída com êxito, a conta de autenticação e os registos associados, incluindo favoritos, registos de carteira, regras de alertas e registos de notificações dos dispositivos, são removidos do serviço ativo. A aplicação também limpa os dados locais associados à conta durante este processo.</p><p>Terminar sessão, desinstalar a aplicação ou revogar o acesso através do fornecedor de autenticação não constitui, por si só, um pedido de eliminação da conta Invest.ao. Podem permanecer cópias em cópias de segurança da infraestrutura ou em registos de segurança até ao fim do respetivo prazo de conservação, ou quando a sua conservação seja exigida por lei. Essas cópias não são utilizadas para manter a sua conta ativa.</p></section>
      <section><h2>7. As suas opções e pedidos</h2><p>Pode consultar e alterar as informações guardadas nas funcionalidades disponíveis na aplicação, gerir notificações, terminar sessão ou eliminar a conta. Consoante a legislação que lhe seja aplicável, pode também solicitar o acesso, a retificação, uma cópia ou a eliminação dos seus dados pessoais, ou opor-se a determinados tratamentos. Poderemos ter de verificar a sua identidade antes de dar seguimento a um pedido relacionado com a conta.</p></section>
      <section><h2>8. Segurança</h2><p>Utilizamos autenticação e controlos de acesso à base de dados específicos de cada conta para limitar o acesso aos dados pessoais guardados. Nenhum serviço em linha ou armazenamento num dispositivo pode ser considerado totalmente seguro. Proteja o seu dispositivo e a sua conta Google ou Apple e evite partilhar o acesso com pessoas em quem não confia.</p></section>
      <section><h2>9. Sítio Web e ligações externas</h2><p>A demonstração interativa da página inicial guarda os favoritos apenas na memória da página; estes são repostos quando a página é recarregada. Essas escolhas não são associadas a uma conta da aplicação. As capturas de ecrã mostram informações registadas no momento da captura, não dados de conta em tempo real. O sítio Web não inclui atualmente rastreadores publicitários nem ferramentas de análise integradas. Os prestadores de infraestrutura podem, ainda assim, tratar registos de pedidos e de segurança.</p><p>Se seguir uma ligação para outro sítio Web, aplicam-se as práticas de privacidade desse sítio.</p></section>
      <section><h2>10. Crianças</h2><p>A Invest.ao não se destina a crianças. Se considerar que uma criança nos forneceu dados pessoais, contacte-nos para que possamos investigar e proceder à eliminação, quando adequado.</p></section>
      <section><h2>11. Alterações a esta política</h2><p>Atualizaremos esta página quando as nossas práticas de tratamento de dados mudarem e alteraremos a data acima. Quando necessário, forneceremos um aviso adicional ou solicitaremos consentimento antes de uma alteração relevante entrar em vigor.</p></section>
      <section><h2>12. Contacto</h2><p>Para questões e pedidos relativos à privacidade, contacte <strong>Informações Invest.AO</strong> através de <a href="mailto:info@invest.ao">info@invest.ao</a>. A eliminação da conta também está disponível diretamente na aplicação, conforme descrito acima.</p></section>
      <footer><Link href="/">Voltar à Invest.ao</Link></footer>
    </main>
  );
}
